#!/bin/sh
# Install all dotfiles into the home directory

DOTFILESDIRREL=$(dirname $0)
cd $DOTFILESDIRREL/..
DOTFILESDIR=$(pwd -P)

[ $(uname -s) = "Darwin" ] && export OSX=1 && export UNIX=1
[ $(uname -s) = "Linux" ] && export LINUX=1 && export UNIX=1
uname -s | grep -q "_NT-" && export WINDOWS=1

for DOTFILE in *; do
  HOMEFILE="$HOME/.$DOTFILE"
  [ -d $DOTFILE ] && DOTFILE="$DOTFILE/"
  DIRFILE="$DOTFILESDIR/$DOTFILE"

  echo $DOTFILE | egrep -q '(^script/$|\.txt$|\.md$|^appconfigs/$)' && continue

  # Don't install some files unless you're also called Steve.
  if echo $USER | grep -vq 'steve'
  then
    echo $DOTFILE | grep -q 'gitconfig-user' && continue
    echo $DOTFILE | grep -q 'ssh' && continue
  fi

  echo $DOTFILE | grep -q '\.sh' \
    && HOMEFILE="$HOME/.$(echo $DOTFILE | sed -e 's/\.sh//')"

  if [ $UNIX ]
  then
    if [ -L "$HOMEFILE" ] && ! [ -d $DOTFILE ]
    then
      ln -sfv "$DIRFILE" "$HOMEFILE"
    else
      rm -rv "$HOMEFILE"
      ln -sv "$DIRFILE" "$HOMEFILE"
    fi
  else
    cp -rv "$DIRFILE" "$HOMEFILE"
  fi
done

# Setup specific app configs

cd appconfigs
for APPCONFIG in *; do
  [ -f $APPCONFIG ] && continue
  echo "Setting up $APPCONFIG"
  "$APPCONFIG/setup"
done

# Install additional things
if ! [ -d $HOME/.spf13-vim-3 ]; then
  echo "Installing spf13-vim3"
  curl https://j.mp/spf13-vim3 -L | sh
fi

if ! [ -d $HOME/.oh-my-zsh ]; then
  echo "Installing oh-my-zsh"
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
fi

# Setup Menumeters

defaults write com.ragingmenace.MenuMeters \
  CPUAverageMultiProcs \
  -int 1

defaults write com.ragingmenace.MenuMeters \
  CPUDisplayMode \
  -int 2

defaults write com.ragingmenace.MenuMeters \
  MemDisplayMode \
  -int 4

defaults write com.ragingmenace.MenuMeters \
  NetDisplayMode \
  -int 2

defaults write com.ragingmenace.MenuMeters \
  com.ragingmenace.MenuMeterDisk \
  -int 0

# General Mac Config

# Minimize to app
defaults write com.apple.dock minimize-to-application -int 1
# Switch to Dark theme
osascript -e 'tell application "System Events" to tell appearance preferences to set dark mode to not dark mode'
# Turn on tap to click by default
sudo defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
sudo defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
sudo defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
# Show battery percent by default
defaults write com.apple.menuextra.battery ShowPercent -string YES
# Minimize to app in tray
defaults write com.apple.dock minimize-to-application -int 1
